pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./animal.html","Executando a exportação &#62; Animal","Animal Navegação: Executando a exportação Animal ",""],
["./atendimento.html","Cadastrando a exportação no sistema &#62; Configurações &#62;&#62; Exportações","Acessar o menu de Configurações &#62;&#62; Exportações, e clicar em Novo:",""],
["./atendimentos.html","Cadastrando a exportação no sistema","Enter topic text here.",""],
["./cadastrando-a-exportacao-no-si.html","Cadastrando a exportação no sistema","Acessar o menu de Configurações &#62;&#62; Exportações:     Clique no botão novo:       Será aberto a tela para o cadastro ...",""],
["./cadastros.html","Executando a exportação","Para a execução basta acessar o menu Procedimentos.",""],
["./consulta-no-banco-de-dados.html","Consulta no banco de dados","De acordo com a solicitação, podemos começar selecionando os campos que são solicitados. Para isso precisamos identificar as tabelas relacionadas ...",""],
["./croquis.html","Fazendo a consulta no banco de dados &#62; Croquis","Enter topic text here.",""],
["./departamento.html","Executando a exportação &#62; Departamento","Destinado a cadastro de novos departamentos. É bem simples fazer um novo cadastro, apenas entrar na aba &#8220;Novo&#8221; colocar Label, Valor e clicando em ...",""],
["./diagnostico.html","Cadastrando a exportação no sistema &#62; Diagnóstico","Enter topic text here.",""],
["./editar.html","Executando a exportação &#62; Departamento &#62; Editar","Editar Navegação: Executando a exportação Departamento Editar ",""],
["./exportacoes.html","Exportações","Funcionalidade do sistema que permite a extração de dados no formato em Excel. Está acessível pelo Menu &#62;&#62; Exportações.",""],
["./georreferenciamento.html","Fazendo a consulta no banco de dados &#62; Georreferenciamento","Enter topic text here.",""],
["./mapa.html","Fazendo a consulta no banco de dados","Enter topic text here.",""],
["./objetivos.html","Objetivos","Criar um relatório que busque o código da propriedade, nome da propriedade, nome do produtor, quantidade de funcionários, estado, município, área ...",""]];
